// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW_vwiaYkiej-jt4J2pDYOcOnXhc7D5MQ',
    appId: '1:519303973856:web:47c75e16298a85e0b6f985',
    messagingSenderId: '519303973856',
    projectId: 'epcvip-mobile-push',
    authDomain: 'epcvip-mobile-push.firebaseapp.com',
    storageBucket: 'epcvip-mobile-push.firebasestorage.app',
    measurementId: 'G-MJ8195N09K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTanWVjWQE-5F1s7BJ8w9ee3z8ZzN4lLo',
    appId: '1:519303973856:android:4bb20168705d1189b6f985',
    messagingSenderId: '519303973856',
    projectId: 'epcvip-mobile-push',
    storageBucket: 'epcvip-mobile-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ZxcT-tvGhogvPklel7ayPLf_OX-ogZo',
    appId: '1:519303973856:ios:6549455899bfc994b6f985',
    messagingSenderId: '519303973856',
    projectId: 'epcvip-mobile-push',
    storageBucket: 'epcvip-mobile-push.firebasestorage.app',
    iosBundleId: 'com.epcvip.epcvipNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ZxcT-tvGhogvPklel7ayPLf_OX-ogZo',
    appId: '1:519303973856:ios:6549455899bfc994b6f985',
    messagingSenderId: '519303973856',
    projectId: 'epcvip-mobile-push',
    storageBucket: 'epcvip-mobile-push.firebasestorage.app',
    iosBundleId: 'com.epcvip.epcvipNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW_vwiaYkiej-jt4J2pDYOcOnXhc7D5MQ',
    appId: '1:519303973856:web:d7dd439396f1685eb6f985',
    messagingSenderId: '519303973856',
    projectId: 'epcvip-mobile-push',
    authDomain: 'epcvip-mobile-push.firebaseapp.com',
    storageBucket: 'epcvip-mobile-push.firebasestorage.app',
    measurementId: 'G-QHNT6RZFMX',
  );
}
